gnet.resolver: deal with getaddrinfo failing
If we have lost connectivity and the resolver is called, then we'll
have an unhandled exception:

    gaierror: [Errno -5] No address associated with hostname

By catching it here, the callback to query() will see there was an
error and will signal an error.

Fixes fd.o#27554

Signed-off-by: Jonny Lamb <jonny.lamb@collabora.co.uk>